server:
  port: 3000

# db: 
#   type: 'postgres'
#   port: 5432
#   database: 'taskmanagement'
db: 
  type: 'mysql'
  port: 3306
  database: 'taskmanagement'
  username: root
  password: '123456'
  synchronize: true

jwt:
  expiresIn: 3600