# db: 
#   host: localhost
#   username: 'postgres'
#   password: 'postgres'
#   synchronize: true

db: 
  type: 'mysql'
  port: 3306
  database: 'taskmanagement'
  username: root
  password: '123456'
  synchronize: false

jwt:
  secret: 'topSecret51'